# Generated by Django 5.1.6 on 2025-02-15 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, unique=True, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Catégorie',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, unique=True, verbose_name='Nom du produit')),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=800)),
                ('price', models.IntegerField(verbose_name='Prix')),
                ('promotion_price', models.IntegerField(blank=True, default=models.IntegerField(verbose_name='Prix'), verbose_name='Prix promotionel')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('is_available', models.BooleanField(verbose_name='Disponible ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='', upload_to='pictures/products')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
            options={
                'verbose_name': 'Produit',
            },
        ),
        migrations.CreateModel(
            name='ProductVariations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('couleur', 'couleur'), ('taille', 'taille')], max_length=100, verbose_name='Type de variation')),
                ('value', models.CharField(max_length=100, verbose_name='Valeur de la variation')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='store.products', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Variation',
            },
        ),
    ]
