# Generated by Django 5.1.6 on 2025-02-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_reviewrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='message',
            field=models.TextField(blank=True, max_length=600, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='subject',
            field=models.CharField(blank=True, max_length=155, verbose_name='Sujet'),
        ),
    ]
