# Generated by Django 5.1.6 on 2025-02-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='promotion_price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Prix promotionel'),
        ),
    ]
