# Generated by Django 5.1.6 on 2025-02-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_products_promotion_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='promotion_price',
            field=models.IntegerField(blank=True, default=models.IntegerField(verbose_name='Prix'), verbose_name='Prix promotionel'),
        ),
    ]
