# Generated by Django 5.1.6 on 2025-02-14 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_products_promotion_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('color', 'couleur'), ('size', 'taille')], max_length=100, verbose_name='Type de variation')),
                ('value', models.CharField(max_length=100, verbose_name='Valeur de la variation')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.products', verbose_name='Produit')),
            ],
        ),
    ]
