# Generated by Django 5.1.6 on 2025-02-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_reviewrating_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='subject',
            field=models.CharField(blank=True, choices=[('Qualité', 'Qualité'), ('Taille', 'Taille'), ('Livraison', 'Livraison'), ('SAV', 'SAV')], max_length=155, verbose_name='Sujet'),
        ),
    ]
