# Generated by Django 5.1.6 on 2025-02-14 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productvariations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariations',
            options={'verbose_name': 'Variation'},
        ),
    ]
