# Generated by Django 5.1.6 on 2025-02-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_productvariations_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariations',
            name='category',
            field=models.CharField(choices=[('couleur', 'couleur'), ('taille', 'taille')], max_length=100, verbose_name='Type de variation'),
        ),
    ]
