# Generated by Django 5.1.6 on 2025-02-23 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('Burkina Faso', 'Burkina Faso'), ('Maroc', 'Maroc'), ('France', 'France')], max_length=50, verbose_name='Pays')),
                ('city', models.CharField(choices=[('Ouagadougou', 'Ouagadougou'), ('Bobo Dioulasso', 'Bobo Dioulasso'), ('Casablanca', 'Casablanca'), ('Rabat', 'Rabat'), ('Agadir', 'Agadir'), ('Marrakech', 'Marrakech'), ('Paris', 'Paris'), ('Marseille', 'Marseille'), ('Nice', 'Nice')], max_length=50, verbose_name='Ville')),
                ('quartier', models.CharField(max_length=70, verbose_name='Quartier')),
                ('picture', models.ImageField(upload_to='profile', verbose_name='Photo de profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
