# Generated by Django 5.1.6 on 2025-02-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quartier',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
