# Generated by Django 5.1.6 on 2025-02-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_quartier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=600, unique=True, verbose_name="Numéro de l'ordre"),
        ),
    ]
