# Generated by Django 5.1.6 on 2025-02-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cartitem_variations'),
        ('store', '0009_alter_productvariations_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(related_name='variations', to='store.productvariations'),
        ),
    ]
